# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jozef/Downloads/vulkan-ADT-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jozef/Downloads/vulkan-ADT-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jozef/Downloads/vulkan-ADT-master/CMakeFiles /home/jozef/Downloads/vulkan-ADT-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jozef/Downloads/vulkan-ADT-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VkDebugger

# Build rule for target.
VkDebugger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VkDebugger
.PHONY : VkDebugger

# fast build rule for target.
VkDebugger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/build
.PHONY : VkDebugger/fast

#=============================================================================
# Target rules for targets named vkGen

# Build rule for target.
vkGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vkGen
.PHONY : vkGen

# fast build rule for target.
vkGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/build
.PHONY : vkGen/fast

#=============================================================================
# Target rules for targets named VkDebuggerLayer

# Build rule for target.
VkDebuggerLayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VkDebuggerLayer
.PHONY : VkDebuggerLayer

# fast build rule for target.
VkDebuggerLayer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/build
.PHONY : VkDebuggerLayer/fast

appUI/appUI.o: appUI/appUI.cpp.o
.PHONY : appUI/appUI.o

# target to build an object file
appUI/appUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appUI.cpp.o
.PHONY : appUI/appUI.cpp.o

appUI/appUI.i: appUI/appUI.cpp.i
.PHONY : appUI/appUI.i

# target to preprocess a source file
appUI/appUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appUI.cpp.i
.PHONY : appUI/appUI.cpp.i

appUI/appUI.s: appUI/appUI.cpp.s
.PHONY : appUI/appUI.s

# target to generate assembly for a file
appUI/appUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appUI.cpp.s
.PHONY : appUI/appUI.cpp.s

appUI/appWindow.o: appUI/appWindow.cpp.o
.PHONY : appUI/appWindow.o

# target to build an object file
appUI/appWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appWindow.cpp.o
.PHONY : appUI/appWindow.cpp.o

appUI/appWindow.i: appUI/appWindow.cpp.i
.PHONY : appUI/appWindow.i

# target to preprocess a source file
appUI/appWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appWindow.cpp.i
.PHONY : appUI/appWindow.cpp.i

appUI/appWindow.s: appUI/appWindow.cpp.s
.PHONY : appUI/appWindow.s

# target to generate assembly for a file
appUI/appWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/appWindow.cpp.s
.PHONY : appUI/appWindow.cpp.s

appUI/callbacks.o: appUI/callbacks.cpp.o
.PHONY : appUI/callbacks.o

# target to build an object file
appUI/callbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/callbacks.cpp.o
.PHONY : appUI/callbacks.cpp.o

appUI/callbacks.i: appUI/callbacks.cpp.i
.PHONY : appUI/callbacks.i

# target to preprocess a source file
appUI/callbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/callbacks.cpp.i
.PHONY : appUI/callbacks.cpp.i

appUI/callbacks.s: appUI/callbacks.cpp.s
.PHONY : appUI/callbacks.s

# target to generate assembly for a file
appUI/callbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/callbacks.cpp.s
.PHONY : appUI/callbacks.cpp.s

appUI/class_apiCall.o: appUI/class_apiCall.cpp.o
.PHONY : appUI/class_apiCall.o

# target to build an object file
appUI/class_apiCall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_apiCall.cpp.o
.PHONY : appUI/class_apiCall.cpp.o

appUI/class_apiCall.i: appUI/class_apiCall.cpp.i
.PHONY : appUI/class_apiCall.i

# target to preprocess a source file
appUI/class_apiCall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_apiCall.cpp.i
.PHONY : appUI/class_apiCall.cpp.i

appUI/class_apiCall.s: appUI/class_apiCall.cpp.s
.PHONY : appUI/class_apiCall.s

# target to generate assembly for a file
appUI/class_apiCall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_apiCall.cpp.s
.PHONY : appUI/class_apiCall.cpp.s

appUI/class_buffer.o: appUI/class_buffer.cpp.o
.PHONY : appUI/class_buffer.o

# target to build an object file
appUI/class_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_buffer.cpp.o
.PHONY : appUI/class_buffer.cpp.o

appUI/class_buffer.i: appUI/class_buffer.cpp.i
.PHONY : appUI/class_buffer.i

# target to preprocess a source file
appUI/class_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_buffer.cpp.i
.PHONY : appUI/class_buffer.cpp.i

appUI/class_buffer.s: appUI/class_buffer.cpp.s
.PHONY : appUI/class_buffer.s

# target to generate assembly for a file
appUI/class_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_buffer.cpp.s
.PHONY : appUI/class_buffer.cpp.s

appUI/class_image.o: appUI/class_image.cpp.o
.PHONY : appUI/class_image.o

# target to build an object file
appUI/class_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_image.cpp.o
.PHONY : appUI/class_image.cpp.o

appUI/class_image.i: appUI/class_image.cpp.i
.PHONY : appUI/class_image.i

# target to preprocess a source file
appUI/class_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_image.cpp.i
.PHONY : appUI/class_image.cpp.i

appUI/class_image.s: appUI/class_image.cpp.s
.PHONY : appUI/class_image.s

# target to generate assembly for a file
appUI/class_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_image.cpp.s
.PHONY : appUI/class_image.cpp.s

appUI/class_memory.o: appUI/class_memory.cpp.o
.PHONY : appUI/class_memory.o

# target to build an object file
appUI/class_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_memory.cpp.o
.PHONY : appUI/class_memory.cpp.o

appUI/class_memory.i: appUI/class_memory.cpp.i
.PHONY : appUI/class_memory.i

# target to preprocess a source file
appUI/class_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_memory.cpp.i
.PHONY : appUI/class_memory.cpp.i

appUI/class_memory.s: appUI/class_memory.cpp.s
.PHONY : appUI/class_memory.s

# target to generate assembly for a file
appUI/class_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_memory.cpp.s
.PHONY : appUI/class_memory.cpp.s

appUI/class_system.o: appUI/class_system.cpp.o
.PHONY : appUI/class_system.o

# target to build an object file
appUI/class_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_system.cpp.o
.PHONY : appUI/class_system.cpp.o

appUI/class_system.i: appUI/class_system.cpp.i
.PHONY : appUI/class_system.i

# target to preprocess a source file
appUI/class_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_system.cpp.i
.PHONY : appUI/class_system.cpp.i

appUI/class_system.s: appUI/class_system.cpp.s
.PHONY : appUI/class_system.s

# target to generate assembly for a file
appUI/class_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/class_system.cpp.s
.PHONY : appUI/class_system.cpp.s

appUI/events.o: appUI/events.cpp.o
.PHONY : appUI/events.o

# target to build an object file
appUI/events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/events.cpp.o
.PHONY : appUI/events.cpp.o

appUI/events.i: appUI/events.cpp.i
.PHONY : appUI/events.i

# target to preprocess a source file
appUI/events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/events.cpp.i
.PHONY : appUI/events.cpp.i

appUI/events.s: appUI/events.cpp.s
.PHONY : appUI/events.s

# target to generate assembly for a file
appUI/events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/events.cpp.s
.PHONY : appUI/events.cpp.s

appUI/main.o: appUI/main.cpp.o
.PHONY : appUI/main.o

# target to build an object file
appUI/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/main.cpp.o
.PHONY : appUI/main.cpp.o

appUI/main.i: appUI/main.cpp.i
.PHONY : appUI/main.i

# target to preprocess a source file
appUI/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/main.cpp.i
.PHONY : appUI/main.cpp.i

appUI/main.s: appUI/main.cpp.s
.PHONY : appUI/main.s

# target to generate assembly for a file
appUI/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/main.cpp.s
.PHONY : appUI/main.cpp.s

appUI/winsock.o: appUI/winsock.cpp.o
.PHONY : appUI/winsock.o

# target to build an object file
appUI/winsock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/winsock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/appUI/winsock.cpp.o
.PHONY : appUI/winsock.cpp.o

appUI/winsock.i: appUI/winsock.cpp.i
.PHONY : appUI/winsock.i

# target to preprocess a source file
appUI/winsock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/winsock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/appUI/winsock.cpp.i
.PHONY : appUI/winsock.cpp.i

appUI/winsock.s: appUI/winsock.cpp.s
.PHONY : appUI/winsock.s

# target to generate assembly for a file
appUI/winsock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/appUI/winsock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/appUI/winsock.cpp.s
.PHONY : appUI/winsock.cpp.s

layer/layer.o: layer/layer.cpp.o
.PHONY : layer/layer.o

# target to build an object file
layer/layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer.cpp.o
.PHONY : layer/layer.cpp.o

layer/layer.i: layer/layer.cpp.i
.PHONY : layer/layer.i

# target to preprocess a source file
layer/layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer.cpp.i
.PHONY : layer/layer.cpp.i

layer/layer.s: layer/layer.cpp.s
.PHONY : layer/layer.s

# target to generate assembly for a file
layer/layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer.cpp.s
.PHONY : layer/layer.cpp.s

layer/layer_data.o: layer/layer_data.cpp.o
.PHONY : layer/layer_data.o

# target to build an object file
layer/layer_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_data.cpp.o
.PHONY : layer/layer_data.cpp.o

layer/layer_data.i: layer/layer_data.cpp.i
.PHONY : layer/layer_data.i

# target to preprocess a source file
layer/layer_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_data.cpp.i
.PHONY : layer/layer_data.cpp.i

layer/layer_data.s: layer/layer_data.cpp.s
.PHONY : layer/layer_data.s

# target to generate assembly for a file
layer/layer_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_data.cpp.s
.PHONY : layer/layer_data.cpp.s

layer/layer_generated.o: layer/layer_generated.cpp.o
.PHONY : layer/layer_generated.o

# target to build an object file
layer/layer_generated.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_generated.cpp.o
.PHONY : layer/layer_generated.cpp.o

layer/layer_generated.i: layer/layer_generated.cpp.i
.PHONY : layer/layer_generated.i

# target to preprocess a source file
layer/layer_generated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_generated.cpp.i
.PHONY : layer/layer_generated.cpp.i

layer/layer_generated.s: layer/layer_generated.cpp.s
.PHONY : layer/layer_generated.s

# target to generate assembly for a file
layer/layer_generated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_generated.cpp.s
.PHONY : layer/layer_generated.cpp.s

layer/layer_messages.o: layer/layer_messages.cpp.o
.PHONY : layer/layer_messages.o

# target to build an object file
layer/layer_messages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_messages.cpp.o
.PHONY : layer/layer_messages.cpp.o

layer/layer_messages.i: layer/layer_messages.cpp.i
.PHONY : layer/layer_messages.i

# target to preprocess a source file
layer/layer_messages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_messages.cpp.i
.PHONY : layer/layer_messages.cpp.i

layer/layer_messages.s: layer/layer_messages.cpp.s
.PHONY : layer/layer_messages.s

# target to generate assembly for a file
layer/layer_messages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebuggerLayer.dir/build.make CMakeFiles/VkDebuggerLayer.dir/layer/layer_messages.cpp.s
.PHONY : layer/layer_messages.cpp.s

layergen/layer_generator.o: layergen/layer_generator.cpp.o
.PHONY : layergen/layer_generator.o

# target to build an object file
layergen/layer_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_generator.cpp.o
.PHONY : layergen/layer_generator.cpp.o

layergen/layer_generator.i: layergen/layer_generator.cpp.i
.PHONY : layergen/layer_generator.i

# target to preprocess a source file
layergen/layer_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_generator.cpp.i
.PHONY : layergen/layer_generator.cpp.i

layergen/layer_generator.s: layergen/layer_generator.cpp.s
.PHONY : layergen/layer_generator.s

# target to generate assembly for a file
layergen/layer_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_generator.cpp.s
.PHONY : layergen/layer_generator.cpp.s

layergen/layer_xml_parser.o: layergen/layer_xml_parser.cpp.o
.PHONY : layergen/layer_xml_parser.o

# target to build an object file
layergen/layer_xml_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_xml_parser.cpp.o
.PHONY : layergen/layer_xml_parser.cpp.o

layergen/layer_xml_parser.i: layergen/layer_xml_parser.cpp.i
.PHONY : layergen/layer_xml_parser.i

# target to preprocess a source file
layergen/layer_xml_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_xml_parser.cpp.i
.PHONY : layergen/layer_xml_parser.cpp.i

layergen/layer_xml_parser.s: layergen/layer_xml_parser.cpp.s
.PHONY : layergen/layer_xml_parser.s

# target to generate assembly for a file
layergen/layer_xml_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/layer_xml_parser.cpp.s
.PHONY : layergen/layer_xml_parser.cpp.s

layergen/main.o: layergen/main.cpp.o
.PHONY : layergen/main.o

# target to build an object file
layergen/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/main.cpp.o
.PHONY : layergen/main.cpp.o

layergen/main.i: layergen/main.cpp.i
.PHONY : layergen/main.i

# target to preprocess a source file
layergen/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/main.cpp.i
.PHONY : layergen/main.cpp.i

layergen/main.s: layergen/main.cpp.s
.PHONY : layergen/main.s

# target to generate assembly for a file
layergen/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/layergen/main.cpp.s
.PHONY : layergen/main.cpp.s

libs/imgui/backends/imgui_impl_glfw.o: libs/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_glfw.o

# target to build an object file
libs/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.o

libs/imgui/backends/imgui_impl_glfw.i: libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.i

libs/imgui/backends/imgui_impl_glfw.s: libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.s

libs/imgui/backends/imgui_impl_vulkan.o: libs/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_vulkan.o

# target to build an object file
libs/imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_vulkan.cpp.o

libs/imgui/backends/imgui_impl_vulkan.i: libs/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_vulkan.cpp.i

libs/imgui/backends/imgui_impl_vulkan.s: libs/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_vulkan.cpp.s

libs/imgui/imgui.o: libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.o

# target to build an object file
libs/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.cpp.o

libs/imgui/imgui.i: libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.i

# target to preprocess a source file
libs/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.cpp.i

libs/imgui/imgui.s: libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.s

# target to generate assembly for a file
libs/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.cpp.s

libs/imgui/imgui_demo.o: libs/imgui/imgui_demo.cpp.o
.PHONY : libs/imgui/imgui_demo.o

# target to build an object file
libs/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_demo.cpp.o
.PHONY : libs/imgui/imgui_demo.cpp.o

libs/imgui/imgui_demo.i: libs/imgui/imgui_demo.cpp.i
.PHONY : libs/imgui/imgui_demo.i

# target to preprocess a source file
libs/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_demo.cpp.i
.PHONY : libs/imgui/imgui_demo.cpp.i

libs/imgui/imgui_demo.s: libs/imgui/imgui_demo.cpp.s
.PHONY : libs/imgui/imgui_demo.s

# target to generate assembly for a file
libs/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_demo.cpp.s
.PHONY : libs/imgui/imgui_demo.cpp.s

libs/imgui/imgui_draw.o: libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.o

# target to build an object file
libs/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.cpp.o

libs/imgui/imgui_draw.i: libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.i

# target to preprocess a source file
libs/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.cpp.i

libs/imgui/imgui_draw.s: libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.s

# target to generate assembly for a file
libs/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.cpp.s

libs/imgui/imgui_tables.o: libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.o

# target to build an object file
libs/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.cpp.o

libs/imgui/imgui_tables.i: libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.i

# target to preprocess a source file
libs/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.cpp.i

libs/imgui/imgui_tables.s: libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.s

# target to generate assembly for a file
libs/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.cpp.s

libs/imgui/imgui_widgets.o: libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.o

# target to build an object file
libs/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.cpp.o

libs/imgui/imgui_widgets.i: libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.i

# target to preprocess a source file
libs/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.cpp.i

libs/imgui/imgui_widgets.s: libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VkDebugger.dir/build.make CMakeFiles/VkDebugger.dir/libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.cpp.s

libs/pugixml/pugixml.o: libs/pugixml/pugixml.cpp.o
.PHONY : libs/pugixml/pugixml.o

# target to build an object file
libs/pugixml/pugixml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/libs/pugixml/pugixml.cpp.o
.PHONY : libs/pugixml/pugixml.cpp.o

libs/pugixml/pugixml.i: libs/pugixml/pugixml.cpp.i
.PHONY : libs/pugixml/pugixml.i

# target to preprocess a source file
libs/pugixml/pugixml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/libs/pugixml/pugixml.cpp.i
.PHONY : libs/pugixml/pugixml.cpp.i

libs/pugixml/pugixml.s: libs/pugixml/pugixml.cpp.s
.PHONY : libs/pugixml/pugixml.s

# target to generate assembly for a file
libs/pugixml/pugixml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vkGen.dir/build.make CMakeFiles/vkGen.dir/libs/pugixml/pugixml.cpp.s
.PHONY : libs/pugixml/pugixml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VkDebugger"
	@echo "... VkDebuggerLayer"
	@echo "... vkGen"
	@echo "... appUI/appUI.o"
	@echo "... appUI/appUI.i"
	@echo "... appUI/appUI.s"
	@echo "... appUI/appWindow.o"
	@echo "... appUI/appWindow.i"
	@echo "... appUI/appWindow.s"
	@echo "... appUI/callbacks.o"
	@echo "... appUI/callbacks.i"
	@echo "... appUI/callbacks.s"
	@echo "... appUI/class_apiCall.o"
	@echo "... appUI/class_apiCall.i"
	@echo "... appUI/class_apiCall.s"
	@echo "... appUI/class_buffer.o"
	@echo "... appUI/class_buffer.i"
	@echo "... appUI/class_buffer.s"
	@echo "... appUI/class_image.o"
	@echo "... appUI/class_image.i"
	@echo "... appUI/class_image.s"
	@echo "... appUI/class_memory.o"
	@echo "... appUI/class_memory.i"
	@echo "... appUI/class_memory.s"
	@echo "... appUI/class_system.o"
	@echo "... appUI/class_system.i"
	@echo "... appUI/class_system.s"
	@echo "... appUI/events.o"
	@echo "... appUI/events.i"
	@echo "... appUI/events.s"
	@echo "... appUI/main.o"
	@echo "... appUI/main.i"
	@echo "... appUI/main.s"
	@echo "... appUI/winsock.o"
	@echo "... appUI/winsock.i"
	@echo "... appUI/winsock.s"
	@echo "... layer/layer.o"
	@echo "... layer/layer.i"
	@echo "... layer/layer.s"
	@echo "... layer/layer_data.o"
	@echo "... layer/layer_data.i"
	@echo "... layer/layer_data.s"
	@echo "... layer/layer_generated.o"
	@echo "... layer/layer_generated.i"
	@echo "... layer/layer_generated.s"
	@echo "... layer/layer_messages.o"
	@echo "... layer/layer_messages.i"
	@echo "... layer/layer_messages.s"
	@echo "... layergen/layer_generator.o"
	@echo "... layergen/layer_generator.i"
	@echo "... layergen/layer_generator.s"
	@echo "... layergen/layer_xml_parser.o"
	@echo "... layergen/layer_xml_parser.i"
	@echo "... layergen/layer_xml_parser.s"
	@echo "... layergen/main.o"
	@echo "... layergen/main.i"
	@echo "... layergen/main.s"
	@echo "... libs/imgui/backends/imgui_impl_glfw.o"
	@echo "... libs/imgui/backends/imgui_impl_glfw.i"
	@echo "... libs/imgui/backends/imgui_impl_glfw.s"
	@echo "... libs/imgui/backends/imgui_impl_vulkan.o"
	@echo "... libs/imgui/backends/imgui_impl_vulkan.i"
	@echo "... libs/imgui/backends/imgui_impl_vulkan.s"
	@echo "... libs/imgui/imgui.o"
	@echo "... libs/imgui/imgui.i"
	@echo "... libs/imgui/imgui.s"
	@echo "... libs/imgui/imgui_demo.o"
	@echo "... libs/imgui/imgui_demo.i"
	@echo "... libs/imgui/imgui_demo.s"
	@echo "... libs/imgui/imgui_draw.o"
	@echo "... libs/imgui/imgui_draw.i"
	@echo "... libs/imgui/imgui_draw.s"
	@echo "... libs/imgui/imgui_tables.o"
	@echo "... libs/imgui/imgui_tables.i"
	@echo "... libs/imgui/imgui_tables.s"
	@echo "... libs/imgui/imgui_widgets.o"
	@echo "... libs/imgui/imgui_widgets.i"
	@echo "... libs/imgui/imgui_widgets.s"
	@echo "... libs/pugixml/pugixml.o"
	@echo "... libs/pugixml/pugixml.i"
	@echo "... libs/pugixml/pugixml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

